stages:
  - deploy

deploy_lambda:
  stage: deploy
  image: hashicorp/terraform:1.8
  script:
    - cd infra/terraform
    - terraform init
    - terraform apply -auto-approve
  variables:
    TF_VAR_gitlab_token: "$GITLAB_TOKEN"
  only:
    - main
