stages:
  - deploy

deploy_lambda:
  stage: deploy
  image: hashicorp/terraform:1.8
  script:
    - cd infra/terraform
    - terraform init -input=false
    - terraform apply -auto-approve -input=false
  variables:
    # --- AWS credentials for Terraform ---
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
    AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"

    # --- Terraform variables passed into Lambda ---
    TF_VAR_git_pat: "$GIT_PAT"
    TF_VAR_git_remote_url: "$GIT_REMOTE_URL"
    TF_VAR_api_base: "$API_BASE"
  only:
    - main
